### ISSUE TITLE
Questions about "feats.yml" file

### ISSUE THREAD

**Issue by daluji** [pierretusseau/OpenLegendTreeView#2]
"name: Craft (I - II)
  prerequisites:
    tier1:
      FeatAttribute:"

I don't understand the FeatAttribute while the entire code doesn't provide it ?

"name: Multi-Target Boon Expert
  prerequisites:
    tier1:
      Feat:
      - Boon Focus
      Feat:
      - Multi-Target Boon Specialist II"

Is this kind of code will work ? It seems weird to me to get a double Feat inside tier1 (in the form of course, not in the substance).

Am I really free to modify any part of this file ? I would like to add fields and standardize all these "Feats". I would also like to know how the changes of skills' level will be handle in the code.

**Comment by KevinBacas** [comment]
Euh je peux toujours faire en sorte de migrer ce fichier à l'intérieur du projet. Pour le moment il est sur un fork du projet officiel sur mon GitHub.

Il faut savoir que toute modification de la structure du fichier entraîne possiblement un changement cassant. Il faut dont que le front soit modifié en parallèle.

Faites comme vous le sentez, je continue de suivre l'issue si jamais vous avez besoin d'une action de ma part ;)

Kévin BACAS

________________________________

**Comment by KevinBacas** [comment]
D'ailleurs, une bonne façon de faire selon moi serait d'avoir le fichier directement dans le dossier `public/`. Comme ça tu es sûr que pour un déploiement donné tu as la version du feats.yml qui est compatible ;)

Comme ça si vous avez une modif à faire, elle peut être faite directement dans le dossier public et ça va vous forcer à le faire marcher. Et la modification ne sera apparente que quand vous aurez mis le code sur un serveur.

Actuellement, si je modifie le fichier sur mon GitHub, ça casse tout :bomb:

**Comment by daluji** [comment]
I guessed that the modification of this file would impact the front, that's why I asked this question and I don't want to break all the work :D 

I don't understand what you say about the `public/` directory, anyway you commit your work if you modify the file, am I right ?

This file is kinda 'locked' ? And when you modify it, even if you make a little change like a space, it breaks everything ? (that's what I understood).

Moreover, it seems weird to me to be forced to supply this file if you have additionals skills, in my opinion, I would created a directory with all skills and a file per skill, like that you only have to add filles if you want to implement more skills.

**Comment by KevinBacas** [comment]
Le feat.yml est sur un dépôt sur mon GitHub. Donc complément dissocié de ce projet. Si on ne met pas à jour les deux dépôts en même temps ça peut poser problème. C'est pourquoi on doit faire attention :)

Kévin BACAS

________________________________

**Comment by pierretusseau** [comment]
Problem solved with the basic addition of "skillLevel" in the skill object.
