### ISSUE TITLE
[Proposal] Make this a PWA

### ISSUE THREAD

**Issue by KevinBacas** [pierretusseau/OpenLegendTreeView#3]
# What is Progressive Web App?
It is basically adding a layer to your application that will cache every assets. This will add User engagement because with chrome on Android for instance, you can add the web app directly to your home screen. It can run the application offline (because your have everything on a local cache).

**Basically, your app is faster and can work offline without any trade-off.**

https://developers.google.com/web/progressive-web-apps/

> A new way to deliver amazing user experiences on the web.

# Is it complicated?
* Add 1 dependency.
* Add 2 files.
* Change 1 line in `package.json`.
* POTG.

# Is there any specific requirements?
You need to be on **HTTPS**. You can use a [let's encrypt SSL certificate](https://letsencrypt.org/). I can set it up.

**Comment by daluji** [comment]
Interesting, especially that the web page doesn't need internet to get data, I think it's a good idea for this project !
POTG Tobleron FTW

**Comment by KevinBacas** [comment]
The web app does require internet for the feat.yml but I guess I can manage to get the latest version when internet comes back ;)

Kévin BACAS

________________________________

**Comment by KevinBacas** [comment]
* First attempt 495f27d098f760d8d17093c04077206ad6de96d4. 
* Add feats.yml caching d752abcd8a88d3503ea7283cefd8e4ac75d28e6d.

ToDo:
* [x] HTTPS
* [x] Check if the network first strategy is working properly

**Comment by KevinBacas** [comment]
@pierretusseau Do you have any HTTPS capabilites? If not, where is your domain hosted?

**Comment by KevinBacas** [comment]
BOOM
* 495f27d098f760d8d17093c04077206ad6de96d4
* d752abcd8a88d3503ea7283cefd8e4ac75d28e6d
* 4d7b6497acee029543eb66493e991f990d4af5b7
* 2d5afc1459b878edd57a18fe04f9245fe6427bf4
